server:
  port: 80
  servlet:
    session:
      timeout: 1800
      cookie:
        max-age: 86400
spring:
  mvc:
    static-path-pattern: /**
  datasource:
    url: jdbc:mysql://192.168.1.90:3306/mydb?useSSL=false&characterEncoding=UTF8
    username: cloud
    password: passwd
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 192.168.1.90
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0

  thymeleaf:
    mode: HTML
    suffix: .html
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.cloud.ssm.system.model

logging:
  config: classpath:log4j2.xml
  level:
    web: trace