server:
  port: 80
  servlet:
    session:
      timeout: 1800
      cookie:
        max-age: 86400
spring:
  application:
    name: 1.0
  mvc:
    static-path-pattern: /**
  datasource:
    url: jdbc:postgresql://192.168.1.90:5432/postgres?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  thymeleaf:
    mode: HTML
    suffix: .html
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.cloud.ssm.system.model
logging:
  config: 
    classpath:logback-spring.xml
  level:
    org.springframework.beans: WARN
    root: INFO
